CREATE TABLE STUDENT(
ID integer not null,
FIRST_NAME varchar(50),
LAST_NAME varchar(50),
CREATE_DATE DATE,
UPDATE_DATE DATE,
primary key(ID)
);
CREATE TABLE COURSE (
ID INTEGER NOT NULL,
COURSE_NAME varchar(255),
COURSE_FEE DOUBLE,
CREATE_DATE DATE,
UPDATE_DATE DATE,
PRIMARY KEY(ID)
);

CREATE TABLE ENROLLMENT (
ID INTEGER NOT NULL, STUDENT_ID INTEGER NOT NULL, COURSE_ID INTEGER NOT NULL, FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID),
FOREIGN KEY (COURSE_ID) REFERENCES COURSE(ID) );